### ISSUE TITLE
Benchmark is not loading for me (linux, chrome 117.0.5938.92)

### ISSUE THREAD

**Issue by cdosborn** [stepheneb/webgl-matrix-benchmarks#23]
![image](https://github.com/stepheneb/webgl-matrix-benchmarks/assets/3847314/f2b11a42-a70b-439b-a41c-f9ef4321790d)

**Comment by stepheneb** [comment]
What is the url you are using for the page? I ask because the error reports a problem when testing twgl -- but at least in my repo I am not testing twgl (though testing twgl is a great idea).

This the the url where my repo is deployed: https://stepheneb.github.io/webgl-matrix-benchmarks/matrix_benchmark.html

Looks like you might be using this fork by @greggman: https://github.com/greggman/webgl-matrix-benchmarks

Which is deployed to this url: https://greggman.github.io/webgl-matrix-benchmarks/matrix_benchmark.html

If you create a new issue at @greggman's repo tag me so I can follow.

FYI: there are a bunch of forks: https://github.com/stepheneb/webgl-matrix-benchmarks/network/members

**Comment by stepheneb** [comment]
Just saw that @greggman doesn't appear to have [issues](https://github.com/greggman/webgl-matrix-benchmarks/pulls) enabled for his fork. Maybe email him??

update: I emailed him at github@greggman.com -- don't know if he is monitoring that address. We'll see.
